services:
  - type: web
    name: mon-site-web
    env: java11
    buildCommand: |
      echo "JAVA_HOME=$JAVA_HOME"
      java -version
      chmod +x gradlew
      ./gradlew assemble
    startCommand: ./gradlew bootRun
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-11-openjdk-amd64
