services:
  - type: web
    name: mon-site-web
    env: java
    buildCommand: chmod +x gradlew && ./gradlew assemble
    startCommand: ./gradlew bootRun
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-11-openjdk-amd64
