services:
  - type: web
    name: mon-site-web
    env: java
    buildCommand: |
      echo "JAVA_HOME is $JAVA_HOME"
      java -version
      chmod +x gradlew
      ./gradlew assemble
    startCommand: ./gradlew bootRun
